# データサイエンス特論 第2回 演習
青山学院大学大学院 理工学研究科 理工学専攻 知能情報コース 修士1年 35626302 森下剛

## 演習2_1

```dir()``` そのオブジェクトが持っている属性やメソッドの一覧を確認するための関数

```id()``` オブジェクトの識別子（メモリアドレスのようなもの）

```type()``` その変数のデータ型を調べる関数

## 演習2_2

In [32]:
x = 10

In [33]:
type(x)

int

In [34]:
id(x)

4388725024

In [35]:
dir(x)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'is_integer',
 'numerator',
 'real',
 'to_bytes']

In [36]:
y = x

In [37]:
id(x)

4388725024

In [38]:
id(y)

4388725024

In [39]:
y = y - 1

In [40]:
print(x)
id(x)

10

4388725024

In [41]:
print(y)
id(y)

9

4388724992

変数xとy=xで定義した変数yのidは等しいことを確認した。
その後y=y-1のように変数yに対して引き算を行うと変数yのidに変更があった。
idはメモリのオブジェクトアドレスを参照する関数なので、y=xのように変数が変数を定義した場合は異なる変数でも同じアドレスが割り当てられていて、変数に対して操作が加わるとアドレスが変更される挙動が確認できた。

## 演習2_3

In [42]:
import pandas as pd

### 演習2_3_1

In [43]:
pearson1 = pd.read_csv('data/pearson.csv')
pearson1

        Father       Son
0     65.04851  59.77827
1     63.25094  63.21404
2     64.95532  63.34242
3     65.75250  62.79238
4     61.13723  64.28113
...        ...       ...
1073  66.99681  70.75232
1074  71.33181  68.26774
1075  71.78314  69.30589
1076  70.73837  69.30199
1077  70.30609  67.01500

[1078 rows x 2 columns]

### 演習2_3_2

In [44]:
pearson0 = pd.read_csv('data/pearson_nh.csv')
pearson0

      65.04851  59.77827
0     63.25094  63.21404
1     64.95532  63.34242
2     65.75250  62.79238
3     61.13723  64.28113
4     63.02254  64.24221
...        ...       ...
1072  66.99681  70.75232
1073  71.33181  68.26774
1074  71.78314  69.30589
1075  70.73837  69.30199
1076  70.30609  67.01500

[1077 rows x 2 columns]

### 演習2_3_3

In [45]:
pearson2 = pearson0

### 演習2_3_4

In [46]:
pearson3 = pd.read_csv('data/pearson_nh.csv', names=["Father", "Son"])

## 演習2_4

In [47]:
pearson4 = pd.read_csv('data/pearson_indexed.csv', index_col=0)
pearson4

         Father       Son
p0001  65.04851  59.77827
p0002  63.25094  63.21404
p0003  64.95532  63.34242
p0004  65.75250  62.79238
p0005  61.13723  64.28113
...         ...       ...
p1074  66.99681  70.75232
p1075  71.33181  68.26774
p1076  71.78314  69.30589
p1077  70.73837  69.30199
p1078  70.30609  67.01500

[1078 rows x 2 columns]

## 演習2_5

### 演習2_5_1

In [48]:
pearson4.iloc[5:10]

         Father       Son
p0006  63.02254  64.24221
p0007  65.37053  64.08231
p0008  64.72398  63.99574
p0009  66.06509  64.61338
p0010  66.96738  63.97944

### 演習2_5_2

In [49]:
pearson4.iloc[:, 1]

p0001    59.77827
p0002    63.21404
p0003    63.34242
p0004    62.79238
p0005    64.28113
           ...
p1074    70.75232
p1075    68.26774
p1076    69.30589
p1077    69.30199
p1078    67.01500
Name: Son, Length: 1078, dtype: float64

### 演習2_5_3

In [50]:
pearson4.iloc[9:20, 0]

p0010    66.96738
p0011    59.00800
p0012    62.93203
p0013    63.67063
p0014    64.07386
p0015    64.68851
p0016    65.15466
p0017    66.37353
p0018    65.57704
p0019    67.36765
p0020    66.75929
Name: Father, dtype: float64

### 演習2_5_4

In [51]:
pearson4.loc["p0100":"p0110"]

         Father       Son
p0100  69.58258  68.06568
p0101  70.39517  68.38188
p0102  71.19284  67.75943
p0103  70.82429  68.59991
p0104  71.65367  67.91483
p0105  73.28133  67.83861
p0106  63.03753  68.77562
p0107  63.66428  69.60782
p0108  65.38311  69.69143
p0109  64.60205  69.41491
p0110  66.40661  69.68931

### 演習2_5_5

In [52]:
pearson4.loc["p0200":"p0210", "Father"]

p0200    70.83996
p0201    72.56944
p0202    67.93353
p0203    67.54033
p0204    72.79855
p0205    62.67482
p0206    68.19196
p0207    65.07215
p0208    73.42952
p0209    62.94125
p0210    62.53667
Name: Father, dtype: float64

### 演習2_5_6

In [53]:
pearson4[(pearson4["Father"] >= 70) & (pearson4["Father"] < 71)]

         Father       Son
p0070  70.35646  66.72679
p0071  70.00643  66.92996
p0101  70.39517  68.38188
p0103  70.82429  68.59991
p0127  70.36485  69.34638
...         ...       ...
p1049  70.70290  72.07098
p1055  70.37520  73.68578
p1062  70.95019  73.81376
p1077  70.73837  69.30199
p1078  70.30609  67.01500

[93 rows x 2 columns]

## 演習2_6

### 演習2_6_1

In [54]:
pearson4["Mother"] = 0
pearson4

         Father       Son  Mother
p0001  65.04851  59.77827       0
p0002  63.25094  63.21404       0
p0003  64.95532  63.34242       0
p0004  65.75250  62.79238       0
p0005  61.13723  64.28113       0
...         ...       ...     ...
p1074  66.99681  70.75232       0
p1075  71.33181  68.26774       0
p1076  71.78314  69.30589       0
p1077  70.73837  69.30199       0
p1078  70.30609  67.01500       0

[1078 rows x 3 columns]

### 演習2_6_2

In [55]:
pearson4.loc["p0000"] = 0
pearson4

         Father       Son  Mother
p0001  65.04851  59.77827       0
p0002  63.25094  63.21404       0
p0003  64.95532  63.34242       0
p0004  65.75250  62.79238       0
p0005  61.13723  64.28113       0
...         ...       ...     ...
p1075  71.33181  68.26774       0
p1076  71.78314  69.30589       0
p1077  70.73837  69.30199       0
p1078  70.30609  67.01500       0
p0000   0.00000   0.00000       0

[1079 rows x 3 columns]

### 演習2_6_3

In [56]:
pearson4 = pearson4.drop("Mother", axis=1)
pearson4

         Father       Son
p0001  65.04851  59.77827
p0002  63.25094  63.21404
p0003  64.95532  63.34242
p0004  65.75250  62.79238
p0005  61.13723  64.28113
...         ...       ...
p1075  71.33181  68.26774
p1076  71.78314  69.30589
p1077  70.73837  69.30199
p1078  70.30609  67.01500
p0000   0.00000   0.00000

[1079 rows x 2 columns]

### 演習2_6_4

In [57]:
pearson4 = pearson4.drop("p1078")
pearson4

         Father       Son
p0001  65.04851  59.77827
p0002  63.25094  63.21404
p0003  64.95532  63.34242
p0004  65.75250  62.79238
p0005  61.13723  64.28113
...         ...       ...
p1074  66.99681  70.75232
p1075  71.33181  68.26774
p1076  71.78314  69.30589
p1077  70.73837  69.30199
p0000   0.00000   0.00000

[1078 rows x 2 columns]

### 演習2_6_5

In [58]:
pearson4 = pearson4.sort_values("Father", ascending=False)
pearson4

         Father       Son
p0158  75.43393  70.09077
p1064  75.17469  73.81739
p0134  74.96203  69.03281
p0639  74.94058  71.40839
p0178  74.80830  71.66455
...         ...       ...
p0854  59.63777  64.94291
p0658  59.48980  64.81735
p0867  59.48391  63.94637
p0011  59.00800  65.24451
p0000   0.00000   0.00000

[1078 rows x 2 columns]

## 演習2_7

In [59]:
pearson1["Father"]

0       65.04851
1       63.25094
2       64.95532
3       65.75250
4       61.13723
          ...
1073    66.99681
1074    71.33181
1075    71.78314
1076    70.73837
1077    70.30609
Name: Father, Length: 1078, dtype: float64

In [60]:
type(pearson1["Father"])

pandas.Series

In [61]:
pearson1[["Father"]]

        Father
0     65.04851
1     63.25094
2     64.95532
3     65.75250
4     61.13723
...        ...
1073  66.99681
1074  71.33181
1075  71.78314
1076  70.73837
1077  70.30609

[1078 rows x 1 columns]

In [62]:
type(pearson1[["Father"]])

pandas.DataFrame

```pearson1["Father"]``` は型が ```pandas.Series``` で、```pearson1[["Father"]]``` は型が ```pandas.DataFrame``` である。Series はラベル付きの1次元データ構造で、DataFrame は行と列からなる2次元のデータ構造である。